local opt = vim.opt
opt.number = true
opt.relativenumber = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.smartcase = true
opt.smartindent = true
opt.spelllang = { "en" }
opt.autoread = true
opt.cursorline = true
opt.wrap = true
