return {
  { "hrsh7th/nvim-cmp", enabled = false },
  { "hrsh7th/cmp-nvim-lsp", enabled = false },
  { "hrsh7th/cmp-buffer", enabled = false },
  { "hrsh7th/cmp-path", enabled = false },
  { "hrsh7th/cmp-path", enabled = false },
  { "nvim-cmp", enabled = false },
  { "garymjr/nvim-snippets", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "folke/ts-comments.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "folke/lazydev.nvim", enabled = false },
  { "Bilal2453/luvit-meta", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "williamboman/mason.nvim", enabled = false },
  { "williamboman/mason-lspconfig.nvim", enabled = false },
}
